# Generated by Django 4.0.5 on 2022-06-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingstrainer',
            options={'verbose_name': 'Настройки тренажера', 'verbose_name_plural': 'Настройки тренажера'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Статистику', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='words',
            options={'ordering': ['date_eng_lessons', 'date_rus_lessons'], 'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
    ]
